#include "SocketClient.h"



SocketClient::SocketClient(string ip, int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F11 begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F11 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void SocketClient::connexion()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F0F begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F0F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

string SocketClient::lireChaine(int finSequence, int timeout)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F1B begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F1B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool SocketClient::ecrireChaine(string chaine)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F25 begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F25 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool SocketClient::estConnecte()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F28 begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F28 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

