#include "Action.h"





/** 
     *  Permet de recupérer le sort lié à une action
     */
Sort Action::getSort()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-103-10-84-37565dd:13daac254e2:-8000:0000000000000E20 begin
{
}
// section 10-103-10-84-37565dd:13daac254e2:-8000:0000000000000E20 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Récupére l'origine du sort
     */
Case Action::getOrigine()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-103-10-84-37565dd:13daac254e2:-8000:0000000000000E22 begin
{
}
// section 10-103-10-84-37565dd:13daac254e2:-8000:0000000000000E22 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Récupére la liste des cibles du sort
     */
void Action::getCible()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-103-10-84-37565dd:13daac254e2:-8000:0000000000000E24 begin
{
}
// section 10-103-10-84-37565dd:13daac254e2:-8000:0000000000000E24 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
