#include "Case.h"

void Case::setProprietaire(Joueur *nouveauProprietaire)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000EED begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000EED end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Case::Case(int defIni, int bonOff, int dissip, int attenu, int mana, int regenDef, int camoufla, Position position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--239a61df:13dc1d51575:-8000:0000000000000F1D begin
{
}
// section -64--88-1-13--239a61df:13dc1d51575:-8000:0000000000000F1D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
