#include "Effet.h"




Effet::Effet(int type, int valeur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--239a61df:13dc1d51575:-8000:0000000000000F37 begin
{
}
// section -64--88-1-13--239a61df:13dc1d51575:-8000:0000000000000F37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
