#include "Partie.h"




Partie::Partie(string nom, int nombrePlace)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-10-3b98f0fe:13dba1c87fc:-8000:0000000000000EB4 begin
{
}
// section -64--88-1-10-3b98f0fe:13dba1c87fc:-8000:0000000000000EB4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Demarre la partie.
     */
void Partie::demarrerPartie()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-11-15711965:13d9366bd46:-8000:0000000000000B21 begin
{
}
// section -64--88-1-11-15711965:13d9366bd46:-8000:0000000000000B21 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Verifie la victoire d'une équipe
     */
bool Partie::verifierVictoire(Equipe equipe)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-11-15711965:13d9366bd46:-8000:0000000000000B23 begin
{
}
// section -64--88-1-11-15711965:13d9366bd46:-8000:0000000000000B23 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Initialise la partie, les different joueurs, les differentes equipes et le terrain
     */
void Partie::initialiser()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-10-3b98f0fe:13dba1c87fc:-8000:0000000000000EB7 begin
{
}
// section -64--88-1-10-3b98f0fe:13dba1c87fc:-8000:0000000000000EB7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
