#include "Plateau.h"


Plateau::Plateau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD3 begin
{
	largeur = hauteur = 2;
	this->initialiserPlateau();
}
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Plateau::Plateau(int largeur, int hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E87 begin
{
	this->hauteur = hauteur;
	this->largeur = largeur;
	this->initialiserPlateau();
}
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Case* Plateau::getCase(int x, int y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E11 begin
{
	Position* position = Position::fabriquePosition(x, y);
	for(int i = 0; i < listeCase.size(); i++)
	{
		if( (*listeCase[i]->getPosition()) == (*position))
		{
			return listeCase[i];
		}
	}
	return NULL;
}

Case* Plateau::getCase(Position const& position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E11 begin
{
	for(int i = 0; i < listeCase.size(); i++)
	{
		if( (*listeCase[i]->getPosition()) == position)
		{
			return listeCase[i];
		}
	}
	return NULL;
}
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E11 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E49 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Plateau::appliquerAction(Action action)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D46 begin
{
	Sort* sort = action.getSort();
	sort->modifierSuivantProprietaire();
	Case* origine = action.getOrigine();
	Joueur* proprietaire = sort->getProprietaire();
	std::vector<Case*> cible;
	int dissipation, nouveauTaux, distance;
	if(origine != NULL)
	{
        //Le sort modifie ses attributs selon la case où il est lancé
		sort->modifierSuivantOrigine(*origine);
		cible = action.getCible();
		for(int i = 0; i < cible.size(); i++)
		{
			dissipation = cible[i]->getEffetDissipation();
			nouveauTaux = Sort::calculeNouveauTauxReussite(dissipation, sort->getPourcentageReussite());
			distance = Position::distance(*(origine->getPosition()), *(cible[i]->getPosition()));
            proprietaire->diminuerMana( distance * sort->getCoupManaParCase() );
			if(proprietaire->estMort())
			{
                //TODO notifier de la mort du joueur (tous les joueurs doivent l'être) car le joueur s'écroule dans d'atroce souffrance
			}
			else
			{
				//tester réussite
                if (Sort::testerReussite(nouveauTaux))
				{
					sort->appliquerSortSurCase(*(cible[i]));
					//TODO notifier joueur de la réussite sur une case
				}
				else
				{
					//TODO notifier joueur de l'echec
				}
			}

		}
	}
}
// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Plateau::nombreCase()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E86 begin
{
	return hauteur*largeur;
}
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E86 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Plateau::nombreCaseControlable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E88 begin
{
	return listeCase.size();
}
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E88 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Plateau::~Plateau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD5 begin
{
	for(int i = 0; i < listeCase.size(); i++)
	{
		delete listeCase[i]; //On supprime toutes les allocation de case
	}
	listeCase.clear();//On vide la liste des case
}
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Plateau::initialiserPlateau()
{
	Case* courante;
	for(int x = 0; x < largeur; x++)
	{
		for(int y = 0; y < hauteur; y++)
		{
            courante = new Case(5, 1, 0, 0, 1, 1, 0, Position::fabriquePosition(x, y));
			listeCase.push_back(courante);
		}
	}
}

int Plateau::getHauteur()
{
    return hauteur;
}

int Plateau::getLargeur()
{
    return largeur;
}

void Plateau::retirerSortDeDureeEcoulee()
{
    for(int i = 0; i < listeCase.size(); i++)
    {
        listeCase[i]->retirerSortEcoule();
    }
}
