#include "Plateau.h"


Plateau::Plateau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD3 begin
{
}
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Plateau::Plateau(int largeur, int hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E87 begin
{
}
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Case Plateau::getCase(int x, int y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E11 begin
{
}
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E11 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Plateau::lancerSort(Case origine, Case cible, Sort sort)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E49 begin
{
}
// section 127-0-0-2-6dd820ac:13d92d99178:-8000:0000000000000E49 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Plateau::appliquerAction(Action action)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D46 begin
{
}
// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Plateau::effectuerAction()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D4B begin
{
}
// section -64--88-1-11--aebb0c8:13d9c89371d:-8000:0000000000000D4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Plateau::nombreCase()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E86 begin
{
}
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E86 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Plateau::nombreCaseControlable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E88 begin
{
}
// section -64--88-1-10-e7a04d0:13db7368584:-8000:0000000000000E88 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Plateau::~Plateau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD5 begin
{
}
// section -64--88-1-13-7473ec88:13da319db56:-8000:0000000000000DD5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
