#include "Serveur.h"

Serveur::Serveur(int port, string ip)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F06 begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000F06 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Serveur::demarrageServeur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000EFE begin
{
}
// section -64--88-1-13--510ac093:13dbbee67dc:-8000:0000000000000EFE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
